### 회원가입 (일반 USER 계정)
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "test",
  "email": "test@example.com",
  "password": "Test123!",
  "userRole": "USER"
}

### 회원가입 (ADMIN 계정)
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@example.com",
  "password": "Admin123!",
  "userRole": "ADMIN"
}

### 로그인 (USER)
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test123!"
}

### 로그인 (ADMIN)
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin123!"
}

### ADMIN이 유저 권한 변경
PATCH http://localhost:8080/admin/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2VyUm9sZSI6IkFETUlOIiwiZXhwIjoxNzUwNzMwNDQ2LCJpYXQiOjE3NTA3MjY4NDZ9.aJnnL9mao9pwMrxpWfONlBf3SeNjbP6-jvmKOwNTuEY

{
  "role": "ADMIN"
}

### 할일 생성 (토큰 필요)
POST http://localhost:8080/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzM2MTk5LCJpYXQiOjE3NTA3MzI1OTl9.wJdStoUeVztGlu9WEQLNFq3Gy2djibQ_TqV3fyJ1HJk

{
  "title": "테스트 할일",
  "contents": "테스트 내용입니다"
}

### 할일 목록 조회 (조건 없음)
GET http://localhost:8080/todos?page=1&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzM2MTk5LCJpYXQiOjE3NTA3MzI1OTl9.wJdStoUeVztGlu9WEQLNFq3Gy2djibQ_TqV3fyJ1HJk

### 할일 목록 조회 (weather만)
GET http://localhost:8080/todos?page=1&size=10&weather=Hail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzI4NjMxLCJpYXQiOjE3NTA3MjUwMzF9.giQbB5fR9cwhfYH2SjkCxJSBI4aazYG7ERwhDKrwGaM

### 할일 목록 조회 (기간만)
GET http://localhost:8080/todos?page=1&size=10&startDate=2025-01-01T00:00&endDate=2025-12-30T23:59:59
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzI4NjMxLCJpYXQiOjE3NTA3MjUwMzF9.giQbB5fR9cwhfYH2SjkCxJSBI4aazYG7ERwhDKrwGaM

### 할일 목록 조회 (whether + 기간)
GET http://localhost:8080/todos?page=1&size=10&weather=Sunny&startDate=2024-01-01T00:00:00&endDate=2024-12-31T23:59:59
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzI4NjMxLCJpYXQiOjE3NTA3MjUwMzF9.giQbB5fR9cwhfYH2SjkCxJSBI4aazYG7ERwhDKrwGaM

### 할일 단건 조회
GET http://localhost:8080/todos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzI4NjMxLCJpYXQiOjE3NTA3MjUwMzF9.giQbB5fR9cwhfYH2SjkCxJSBI4aazYG7ERwhDKrwGaM



### 댓글 작성 (todoId를 위에서 받은 할일 ID로 변경)
POST http://localhost:8080/todos/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzM2MTk5LCJpYXQiOjE3NTA3MzI1OTl9.wJdStoUeVztGlu9WEQLNFq3Gy2djibQ_TqV3fyJ1HJk

{
  "contents": "첫 번째 댓글입니다!"
}

### 댓글 목록 조회
GET http://localhost:8080/todos/1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzM2MTk5LCJpYXQiOjE3NTA3MzI1OTl9.wJdStoUeVztGlu9WEQLNFq3Gy2djibQ_TqV3fyJ1HJk

### 유저 조회 (토큰 필요)
GET http://localhost:8080/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwidXNlclJvbGUiOiJVU0VSIiwiZXhwIjoxNzUwNzI4NjMxLCJpYXQiOjE3NTA3MjUwMzF9.giQbB5fR9cwhfYH2SjkCxJSBI4aazYG7ERwhDKrwGaM

### 비밀번호 변경 (토큰 필요)
PUT http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "Test123!",
  "newPassword": "NewTest123!"
}